# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='profiles/'),
        ),
    ]
