# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-20 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_hood_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
