# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-21 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_blog'),
        ('neighbourhood', '0002_auto_20200821_0847'),
    ]

    operations = [
    ]
